name: Run EE Server
description: Run EE server. Returns once server is ready. Only tested on Linux and macOS
# NOTE: do not share this server container with others
# since it's using the default admin / admin credentials
inputs:
  # All inputs in composite actions are strings
  server-tag:
    description: Server version to use
    required: false
    default: latest
  container-repo-url:
    required: false
    description: Container repo url
    default: artifact.aerospike.io
  jfrog-platform-url:
    description: JFrog platform url
    required: false
    default: https://aerospike.jfrog.io
  oidc-provider:
    description: OIDC provider name
    required: true
  oidc-audience:
    description: OIDC audience
    required: true
  container-name:
    default: aerospike
    required: false
    description: Name for test container
  server-type:
    required: false
    default: aerospike-server-enterprise
    description: Server type `aerospike-server` or `aerospike-server-enterprise`
  strong-consistency:
    required: false
    default: "1"
    description: Enable strong consistency (1 or 0)
  security:
    required: false
    default: "0"
    description: Enable security (1 or 0)
  server-image:
    required: false
    default: ""
    description: Custom full docker image name (e.g., aerospike.jfrog.io/database-docker-virtual/aerospike-server-enterprise:8.1.1.0-rc27_1). Overrides container-repo-url, server-type, and server-tag if provided.

runs:
  using: composite
  steps:
  - name: Set up JFrog credentials
    id: setup-jfrog-cli
    uses: jfrog/setup-jfrog-cli@5b06f730cc5a6f55d78b30753f8583454b08c0aa # v4.8.1
    env:
      JF_URL: ${{ inputs.jfrog-platform-url }}
      JF_PROJECT: database
    with:
      oidc-provider-name: ${{ inputs.oidc-provider }}
      oidc-audience: ${{ inputs.oidc-audience }}

  - name: Docker login to container repo
    run: docker login ${{ inputs.container-repo-url }} --username ${{ steps.setup-jfrog-cli.outputs.oidc-user }} --password ${{ steps.setup-jfrog-cli.outputs.oidc-token }}
    shell: bash

  - name: Set image name
    run: |
      if [ -n "${{ inputs.server-image }}" ]; then
        echo IMAGE_FULL_NAME=${{ inputs.server-image }} >> $GITHUB_ENV
      else
        echo IMAGE_FULL_NAME=${{ inputs.container-repo-url }}/docker/${{ inputs.server-type }}:${{ inputs.server-tag }} >> $GITHUB_ENV
      fi
    shell: bash

  - name: Run EE server setup script
    run: STRONG_CONSISTENCY=${{ inputs.strong-consistency }} SECURITY=${{ inputs.security }} bash ./run-ee-server.bash
    working-directory: .github/workflows/docker-setup
    shell: bash
    env:
      CONTAINER_NAME: ${{ inputs.container-name }}

  - run: docker logs ${{ inputs.container-name }}
    shell: bash
